#!/usr/bin/env bash

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config pointer_modifier            mod1
bspc config ignore_ewmh_focus           true
bspc config directional_focus_tightness low
bspc config focus_follows_pointer       true
bspc config external_rules_command      $(which bspwm_external_rules)

bspc config border_width                0
bspc config window_gap                  6
bspc config bottom_padding              0
bspc config top_padding                 -5
bspc config left_padding                0
bspc config right_padding               0

bspc rule -a Brave-browser-dev desktop='^2' follow=off
bspc rule -a St:calcurse state=floating
bspc rule -a St:ncmpcpp state=floating
bspc rule -a Thunar state=floating
bspc rule -a code-oss desktop='^1' follow=off
bspc rule -a qBittorrent desktop='^10' follow=off
bspc rule -a discord desktop='^8' follow=off

killall -q tint2
tint2 -c ~/.config/tint2/tint2rc.top &
tint2 -c ~/.config/tint2/tint2rc.bottom &

